In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)
plt.style.use('seaborn-v0_8')

print("All libraries loaded successfully!")

All libraries loaded successfully!

In [73]:
# Read directly from zip — no unzipping needed
df = pd.read_csv("../listings.csv.gz", compression='gzip', low_memory=False)

print(f"Shape: {df.shape}")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

Shape: (37147, 79)
Rows: 37,147
Columns: 79

In [74]:
df.head(3)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250401230149,2025-04-02,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,Renovated apt home in elevator building.,Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/3949d073-a02e...,2787,https://www.airbnb.com/users/show/2787,John,2008-09-07,"New York, NY",Educated professional living in Brooklyn. I l...,within an hour,100%,81%,f,https://a0.muscache.com/im/pictures/user/86745...,https://a0.muscache.com/im/pictures/user/86745...,Gravesend,4.00,13.00,"['email', 'phone']",t,t,Neighborhood highlights,Kensington,Brooklyn,40.65,-73.97,Private room in rental unit,Private room,2,1.00,1 private bath,1.00,1.00,"[""Microwave"", ""Portable fans"", ""Free street pa...",$128.00,30,730,30.00,30.00,730.00,730.00,30.00,730.00,NaN,t,23,53,83,358,2025-04-02,9,0,0,267,0,0,0.00,2015-12-04,2018-10-19,4.89,4.88,5.00,5.00,5.00,4.75,4.88,NaN,f,4,0,4,0,0.08
1,6872,https://www.airbnb.com/rooms/6872,20250401230149,2025-04-02,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,https://www.airbnb.com/users/show/16104,Kahshanna,2009-05-07,"New York, NY",A former life in fashion and wellness has left...,within a few hours,100%,33%,f,https://a0.muscache.com/im/pictures/user/d865a...,https://a0.muscache.com/im/pictures/user/d865a...,East Harlem,2.00,2.00,"['email', 'phone', 'work_email']",t,f,Neighborhood highlights,East Harlem,Manhattan,40.80,-73.94,Private room in condo,Private room,1,1.00,1 shared bath,1.00,1.00,"[""Dryer"", ""Elevator"", ""Hangers"", ""Hot water"", ...",$59.00,30,180,30.00,30.00,180.00,180.00,30.00,180.00,NaN,t,23,53,83,83,2025-04-02,1,0,0,83,0,0,0.00,2022-06-05,2022-06-05,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,f,2,0,2,0,0.03
2,7064,https://www.airbnb.com/rooms/7064,20250401230149,2025-04-02,previous scrape,"Amazing location! Wburg. Large, bright & tranquil","Large, private loft-like room in a spacious 2-...","- One stop from the East Village, Lower East S...",https://a0.muscache.com/pictures/13708959/7e74...,17297,https://www.airbnb.com/users/show/17297,Joelle,2009-05-15,"New York, NY",I have lived in the same apartment in Brooklyn...,a few days or more,0%,0%,f,https://a0.muscache.com/im/users/17297/profile...,https://a0.muscache.com/im/users/17297/profile...,Williamsburg,2.00,2.00,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Williamsburg,Brooklyn,40.71,-73.96,Private room in loft,Private room,2,NaN,1 shared bath,1.00,NaN,"[""Dryer"", ""Air conditioning"", ""Hangers"", ""Dish...",NaN,30,45,30.00,30.00,45.00,45.00,30.00,45.00,NaN,t,0,0,0,0,2025-04-02,13,0,0,0,0,0,NaN,2010-08-17,2022-09-12,4.91,5.00,4.91,5.00,5.00,5.00,5.00,NaN,f,2,0,2,0,0.07

In [75]:
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100).round(2)

summary = pd.DataFrame({
    'missing_count':missing,
    'missing_pct':missing_pct
}).sort_values('missing_pct',ascending=False)

print(summary[summary['missing_count'] > 0])

                             missing_count  missing_pct
calendar_updated                     37147       100.00
license                              31778        85.55
neighborhood_overview                17560        47.27
neighbourhood                        17559        47.27
host_response_time                   15798        42.53
host_response_rate                   15798        42.53
host_about                           15778        42.47
estimated_revenue_l365d              15018        40.43
price                                15018        40.43
beds                                 14935        40.21
bathrooms                            14781        39.79
host_acceptance_rate                 14628        39.38
review_scores_location               11692        31.47
review_scores_checkin                11689        31.47
review_scores_value                  11691        31.47
review_scores_accuracy               11685        31.46
review_scores_communication          11681        31.45
review_scores_cleanliness            11676        31.43
reviews_per_month                    11675        31.43
review_scores_rating                 11675        31.43
first_review                         11675        31.43
last_review                          11675        31.43
host_location                         7631        20.54
host_neighbourhood                    7412        19.95
bedrooms                              5964        16.06
has_availability                      5606        15.09
description                            981         2.64
host_is_superhost                      418         1.13
bathrooms_text                          31         0.08
host_since                              27         0.07
host_name                               25         0.07
host_listings_count                     27         0.07
host_identity_verified                  27         0.07
host_verifications                      27         0.07
host_has_profile_pic                    27         0.07
host_picture_url                        27         0.07
host_total_listings_count               27         0.07
host_thumbnail_url                      27         0.07
minimum_minimum_nights                  21         0.06
minimum_nights_avg_ntm                  21         0.06
minimum_maximum_nights                  21         0.06
maximum_minimum_nights                  21         0.06
maximum_maximum_nights                  21         0.06
maximum_nights_avg_ntm                  21         0.06
name                                     2         0.01
picture_url                              1         0.00

In [63]:
# checking why the price column is null
print(df['price'].head(20))
print(df['price'].dtype)
print(df['price'].unique()[:10])

0     $128.00
1      $59.00
2         NaN
3     $290.00
4     $170.00
5     $175.00
6      $90.00
7         NaN
8     $240.00
9      $97.00
10     $67.00
11    $195.00
12        NaN
13    $170.00
14    $117.00
15    $223.00
16    $298.00
17        NaN
18    $120.00
19    $115.00
Name: price, dtype: str
str
<StringArray>
['$128.00',  '$59.00',       nan, '$290.00', '$170.00', '$175.00',  '$90.00',
 '$240.00',  '$97.00',  '$67.00']
Length: 10, dtype: str

In [64]:
import os

# Check file size
size = os.path.getsize("../listings.csv")
print(f"File size: {size / 1024 / 1024:.2f} MB")

File size: 5.58 MB

In [65]:
detailed_listings = pd.read_csv('../listings.csv')

In [66]:
detailed_listings.shape

(37147, 18)

In [67]:
detailed_listings.isna().sum()

id                                    0
name                                  2
host_id                               0
host_name                            25
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                             15018
minimum_nights                        0
number_of_reviews                     0
last_review                       11675
reviews_per_month                 11675
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                           31778
dtype: int64

In [68]:
detailed_listings.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2539,Superfast Wi-Fi. Clean & quiet home by the park,2787,John,Brooklyn,Kensington,40.65,-73.97,Private room,128.00,30,9,2018-10-19,0.08,4,358,0,NaN
1,6848,Only 2 stops to Manhattan studio,15991,Allen,Brooklyn,Williamsburg,40.71,-73.95,Entire home/apt,97.00,30,194,2024-10-05,1.00,1,204,3,NaN
2,7064,"Amazing location! Wburg. Large, bright & tranquil",17297,Joelle,Brooklyn,Williamsburg,40.71,-73.96,Private room,NaN,30,13,2022-09-12,0.07,2,0,0,NaN
3,7801,Sunny Williamsburg Loft with Sauna,21207,Chaya,Brooklyn,Williamsburg,40.72,-73.96,Entire home/apt,290.00,30,13,2024-07-31,0.07,1,0,1,NaN
4,51438,1 Bedroom in 2 Bdrm Apt- Upper East,236421,Jessica,Manhattan,Upper East Side,40.77,-73.95,Private room,NaN,30,0,NaN,NaN,2,0,0,NaN

### the detailed file is the listings.csv.gz and the price is missing is 40% so going with it.

## Price filtering and cleaning

In [69]:
# Drop 100% missing and very high missing columns
cols_to_drop = [
    'calendar_updated',      # 100% missing
    'license',               # 85% missing, not useful for analysis
    'neighborhood_overview', # 47% missing, free text not needed
    'estimated_revenue_l365d' # 40% missing, we'll calculate our own
]

df = df.drop(columns=cols_to_drop)
print(f"Shape after dropping useless columns: {df.shape}")

Shape after dropping useless columns: (37147, 75)

In [70]:
# Remove listings with no price — can't analyze them
df = df.dropna(subset=['price'])
print(f"Shape after dropping null prices: {df.shape}")
print(f"Price sample:\n{df['price'].head(10)}")

Shape after dropping null prices: (22129, 75)
Price sample:
0     $128.00
1      $59.00
3     $290.00
4     $170.00
5     $175.00
6      $90.00
8     $240.00
9      $97.00
10     $67.00
11    $195.00
Name: price, dtype: str

In [77]:
df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\laran\AppData\Local\Temp\ipykernel_26628\1233574569.py:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)

In [81]:
# Show how many listings are above $10,000
total = len(df)
above_10k = len(df[df['price'] > 10000])
pct = (above_10k / total) * 100

print(f"Listings above $10,000: {above_10k} ({pct:.2f}% of total)")
print(f"\nSample of extreme prices:")
print(df[df['price'] > 10000][['name', 'neighbourhood_cleansed', 'room_type', 'price']].head(10))

Listings above $10,000: 9 (0.02% of total)

Sample of extreme prices:
                                                    name  \
18448  WELCOME HOME 15 MINUTES  TO MANHATTAN  BOOK TODAY
23098                             Four Bedroom Penthouse
27562                   Brand New Five Bedroom Penthouse
27624                      1-Bedroom Hotel Suite - 1 bed
27625                 2 Connecting Hotel Suites - 2 beds
27626                     1-Bedroom Hotel Suite - 2 beds
27790                        3 Bedroom 3 level penthouse
27791                        6 Bedroom Upper East Estate
29531                   Real Housewives Star NY Townhome

      neighbourhood_cleansed        room_type    price
18448               Longwood     Private room 11292.00
23098      Battery Park City  Entire home/apt 13600.00
27562        Lower East Side  Entire home/apt 10688.00
27624                   SoHo     Private room 20000.00
27625                   SoHo     Private room 20000.00
27626                   SoHo     Private room 20000.00
27790        Upper East Side  Entire home/apt 14399.00
27791        Upper East Side  Entire home/apt 15200.00
29531        Upper East Side  Entire home/apt 15155.00

Listings priced above $10,000 per night are removed for the following reasons:

1. Statistical outliers — NYC median Airbnb price is around $150-200/night. 
   Prices above $10,000 are extreme outliers that would heavily skew 
   averages, visualizations, and any regression models.

2. Likely data errors — Some hosts enter incorrect prices (e.g. $10,000 
   instead of $100) or use placeholder values. These are not representative 
   of real market pricing.

3. Different market segment — Ultra-luxury rentals above $10,000/night 
   represent a completely different market (private mansions, penthouses) 
   that is not relevant to a typical Airbnb market analysis.

4. Volume is negligible — Listings above $10,000 represent less than 0.1% 
   of all listings, so removing them has no meaningful impact on the dataset.

In [82]:
df = df[(df['price'] > 0) & (df['price'] < 10000)]

print(f"Price range: ${df['price'].min()} — ${df['price'].max()}")
print(f"Median price: ${df['price'].median()}")
print(f"Rows remaining: {len(df):,}")

Price range: $8.0 — $9129.0
Median price: $145.0
Rows remaining: 22,118

## Fix date columns

In [83]:
date_cols = ['host_since', 'first_review', 'last_review']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print("Date columns fixed:")
print(df[date_cols].dtypes)

Date columns fixed:
host_since      datetime64[us]
first_review    datetime64[us]
last_review     datetime64[us]
dtype: object

In [84]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250401230149,2025-04-02,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,Renovated apt home in elevator building.,Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/3949d073-a02e...,2787,https://www.airbnb.com/users/show/2787,John,2008-09-07,"New York, NY",Educated professional living in Brooklyn. I l...,within an hour,100%,81%,f,https://a0.muscache.com/im/pictures/user/86745...,https://a0.muscache.com/im/pictures/user/86745...,Gravesend,4.00,13.00,"['email', 'phone']",t,t,Neighborhood highlights,Kensington,Brooklyn,40.65,-73.97,Private room in rental unit,Private room,2,1.00,1 private bath,1.00,1.00,"[""Microwave"", ""Portable fans"", ""Free street pa...",128.00,30,730,30.00,30.00,730.00,730.00,30.00,730.00,NaN,t,23,53,83,358,2025-04-02,9,0,0,267,0,0,0.00,2015-12-04,2018-10-19,4.89,4.88,5.00,5.00,5.00,4.75,4.88,NaN,f,4,0,4,0,0.08
1,6872,https://www.airbnb.com/rooms/6872,20250401230149,2025-04-02,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,https://www.airbnb.com/users/show/16104,Kahshanna,2009-05-07,"New York, NY",A former life in fashion and wellness has left...,within a few hours,100%,33%,f,https://a0.muscache.com/im/pictures/user/d865a...,https://a0.muscache.com/im/pictures/user/d865a...,East Harlem,2.00,2.00,"['email', 'phone', 'work_email']",t,f,Neighborhood highlights,East Harlem,Manhattan,40.80,-73.94,Private room in condo,Private room,1,1.00,1 shared bath,1.00,1.00,"[""Dryer"", ""Elevator"", ""Hangers"", ""Hot water"", ...",59.00,30,180,30.00,30.00,180.00,180.00,30.00,180.00,NaN,t,23,53,83,83,2025-04-02,1,0,0,83,0,0,0.00,2022-06-05,2022-06-05,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,f,2,0,2,0,0.03
3,7801,https://www.airbnb.com/rooms/7801,20250401230149,2025-04-02,city scrape,Sunny Williamsburg Loft with Sauna,A huge loft in a repurposed factory building i...,We've lived here for over 15 years and love Wi...,https://a0.muscache.com/pictures/miso/Hosting-...,21207,https://www.airbnb.com/users/show/21207,Chaya,2009-06-12,"New York, NY",We're a couple in our thirties who love to tra...,within an hour,100%,96%,t,https://a0.muscache.com/im/pictures/user/d0391...,https://a0.muscache.com/im/pictures/user/d0391...,Williamsburg,4.00,4.00,"['email', 'phone']",t,t,Neighborhood highlights,Williamsburg,Brooklyn,40.72,-73.96,Entire place,Entire home/apt,2,1.00,1 bath,0.00,1.00,"[""Microwave"", ""Free street parking"", ""Drying r...",290.00,30,120,30.00,30.00,120.00,120.00,30.00,120.00,NaN,t,0,0,0,0,2025-04-02,13,1,0,0,1,60,17400.00,2009-08-09,2024-07-31,4.91,4.78,4.67,4.89,4.78,5.00,4.89,NaN,f,1,1,0,0,0.07
4,8490,https://www.airbnb.com/rooms/8490,20250401230149,2025-04-02,city scrape,"Maison des Sirenes1,bohemian, luminous apartment",Soak up the modern and vintage charm<br />of t...,NaN,https://a0.muscache.com/pictures/1d0d9773-c829...,25183,https://www.airbnb.com/users/show/25183,Nathalie,2009-07-10,"New York, NY",I am French and have been living in Ny for 10...,within an hour,100%,NaN,f,https://a0.muscache.com/im/users/25183/profile...,https://a0.muscache.com/im/users/25183/profile...,Bedford-Stuyvesant,2.00,3.00,"['email', 'phone']",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.68,-73.94,Entire loft,Entire home/apt,5,1.00,1 bath,1.00,4.00,"[""Microwave"", ""Free street parking"", ""Drying r...",170.00,30,1125,30.00,30.00,1125.00,1125.00,30.00,1125.00,NaN,t,3,5,6,165,2025-04-02,190,0,0,75,0,0,0.00,2009-08-25,2023-10-16,4.77,4.83,4.74,4.88,4.88,4.67,4.76,NaN,f,2,2,0,0,1.00
5,9357,https://www.airbnb.com/rooms/9357,20250401230149,2025-04-02,city scrape,Midtown Pied-a-terre,PLEASE DO NOT REQUEST TO BOOK UNTIL WE HAVE ME...,Quiet residential block near many restaurants ...,https://a0.muscache.com/pictures/90036/4e60665...,30193,https://www.airbnb.com/users/show/30193,Tommi Laurelle,2009-08-06,"New York, NY",I am a spirit-minded alternative health practi...,NaN,NaN,0%,f,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Hell's Kitchen,1.00,1.00,"['email', 'phone']",t,t,Neighborhood highlights,Hell's Kitchen,Manhattan,40.77,-73.99,Entire rental unit,Entire home/apt,2,1.00,1 bath,NaN,1.00,"[""Free street parking"", ""Extra pillows and bla...",175.00,30,120,30.00,30.00,120.00,120.00,30.00,120.00,NaN,t,0,0,0,0,2025-04-02,58,0,0,0,0,0,0.00,2009-10-04,2017-08-13,4.52,4.68,4.16,4.97,5.00,4.95,4.58,NaN,f,1,1,0,0,0.31

## Fixing percentage Rates

In [85]:
for col in ['host_response_rate', 'host_acceptance_rate']:
    df[col] = df[col].replace('%', '', regex=True)
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(df[['host_response_rate', 'host_acceptance_rate']].describe())

       host_response_rate  host_acceptance_rate
count            18041.00              18721.00
mean                93.26                 77.59
std                 19.47                 28.47
min                  0.00                  0.00
25%                 99.00                 65.00
50%                100.00                 90.00
75%                100.00                100.00
max                100.00                100.00

## Fill numeric nulls

In [86]:
# Reviews — 0 for listings with no reviews yet
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)

# Beds and bedrooms — fill with median
df['beds'] = df['beds'].fillna(df['beds'].median())
df['bedrooms'] = df['bedrooms'].fillna(df['bedrooms'].median())
df['bathrooms'] = df['bathrooms'].fillna(df['bathrooms'].median())

print("Numeric nulls filled")
print(df[['beds', 'bedrooms', 'bathrooms']].isnull().sum())

Numeric nulls filled
beds         0
bedrooms     0
bathrooms    0
dtype: int64

## Categorical nulls

In [87]:
df['neighbourhood'] = df['neighbourhood'].fillna(df['neighbourhood_cleansed'])
df['host_about'] = df['host_about'].fillna('Not provided')
df['description'] = df['description'].fillna('Not provided')
df['bathrooms_text'] = df['bathrooms_text'].fillna('Not provided')

print("Categorical nulls filled")

Categorical nulls filled

## Fixing is boolean columns

In [92]:
# Convert t/f to True/False boolean
for col in ['host_is_superhost','instant_bookable','has_availability','host_has_profile_pic','host_verifications','host_identity_verified']:
    df[col] = df[col].map({'t': True, 'f': False})
    df[col] = df[col].fillna(False)

# print(df['host_is_superhost'].value_counts())

In [91]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250401230149,2025-04-02,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,Renovated apt home in elevator building.,Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/3949d073-a02e...,2787,https://www.airbnb.com/users/show/2787,John,2008-09-07,"New York, NY",Educated professional living in Brooklyn. I l...,within an hour,100.00,81.00,False,https://a0.muscache.com/im/pictures/user/86745...,https://a0.muscache.com/im/pictures/user/86745...,Gravesend,4.00,13.00,False,True,t,Neighborhood highlights,Kensington,Brooklyn,40.65,-73.97,Private room in rental unit,Private room,2,1.00,1 private bath,1.00,1.00,"[""Microwave"", ""Portable fans"", ""Free street pa...",128.00,30,730,30.00,30.00,730.00,730.00,30.00,730.00,NaN,True,23,53,83,358,2025-04-02,9,0,0,267,0,0,0.00,2015-12-04,2018-10-19,4.89,4.88,5.00,5.00,5.00,4.75,4.88,NaN,False,4,0,4,0,0.08
1,6872,https://www.airbnb.com/rooms/6872,20250401230149,2025-04-02,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,https://www.airbnb.com/users/show/16104,Kahshanna,2009-05-07,"New York, NY",A former life in fashion and wellness has left...,within a few hours,100.00,33.00,False,https://a0.muscache.com/im/pictures/user/d865a...,https://a0.muscache.com/im/pictures/user/d865a...,East Harlem,2.00,2.00,False,True,f,Neighborhood highlights,East Harlem,Manhattan,40.80,-73.94,Private room in condo,Private room,1,1.00,1 shared bath,1.00,1.00,"[""Dryer"", ""Elevator"", ""Hangers"", ""Hot water"", ...",59.00,30,180,30.00,30.00,180.00,180.00,30.00,180.00,NaN,True,23,53,83,83,2025-04-02,1,0,0,83,0,0,0.00,2022-06-05,2022-06-05,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,False,2,0,2,0,0.03
3,7801,https://www.airbnb.com/rooms/7801,20250401230149,2025-04-02,city scrape,Sunny Williamsburg Loft with Sauna,A huge loft in a repurposed factory building i...,We've lived here for over 15 years and love Wi...,https://a0.muscache.com/pictures/miso/Hosting-...,21207,https://www.airbnb.com/users/show/21207,Chaya,2009-06-12,"New York, NY",We're a couple in our thirties who love to tra...,within an hour,100.00,96.00,False,https://a0.muscache.com/im/pictures/user/d0391...,https://a0.muscache.com/im/pictures/user/d0391...,Williamsburg,4.00,4.00,False,True,t,Neighborhood highlights,Williamsburg,Brooklyn,40.72,-73.96,Entire place,Entire home/apt,2,1.00,1 bath,0.00,1.00,"[""Microwave"", ""Free street parking"", ""Drying r...",290.00,30,120,30.00,30.00,120.00,120.00,30.00,120.00,NaN,True,0,0,0,0,2025-04-02,13,1,0,0,1,60,17400.00,2009-08-09,2024-07-31,4.91,4.78,4.67,4.89,4.78,5.00,4.89,NaN,False,1,1,0,0,0.07
4,8490,https://www.airbnb.com/rooms/8490,20250401230149,2025-04-02,city scrape,"Maison des Sirenes1,bohemian, luminous apartment",Soak up the modern and vintage charm<br />of t...,NaN,https://a0.muscache.com/pictures/1d0d9773-c829...,25183,https://www.airbnb.com/users/show/25183,Nathalie,2009-07-10,"New York, NY",I am French and have been living in Ny for 10...,within an hour,100.00,NaN,False,https://a0.muscache.com/im/users/25183/profile...,https://a0.muscache.com/im/users/25183/profile...,Bedford-Stuyvesant,2.00,3.00,False,True,t,Bedford-Stuyvesant,Bedford-Stuyvesant,Brooklyn,40.68,-73.94,Entire loft,Entire home/apt,5,1.00,1 bath,1.00,4.00,"[""Microwave"", ""Free street parking"", ""Drying r...",170.00,30,1125,30.00,30.00,1125.00,1125.00,30.00,1125.00,NaN,True,3,5,6,165,2025-04-02,190,0,0,75,0,0,0.00,2009-08-25,2023-10-16,4.77,4.83,4.74,4.88,4.88,4.67,4.76,NaN,False,2,2,0,0,1.00
5,9357,https://www.airbnb.com/rooms/9357,20250401230149,2025-04-02,city scrape,Midtown Pied-a-terre,PLEASE DO NOT REQUEST TO BOOK UNTIL WE HAVE ME...,Quiet residential block near many restaurants ...,https://a0.muscache.com/pictures/90036/4e60665...,30193,https://www.airbnb.com/users/show/30193,Tommi Laurelle,2009-08-06,"New York, NY",I am a spirit-minded alternative health practi...,NaN,NaN,0.00,False,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Hell's Kitchen,1.00,1.00,False,True,t,Neighborhood highlights,Hell's Kitchen,Manhattan,40.77,-73.99,Entire rental unit,Entire home/apt,2,1.00,1 bath,1.00,1.00,"[""Free street parking"", ""Extra pillows and bla...",175.00,30,120,30.00,30.00,120.00,120.00,30.00,120.00,NaN,True,0,0,0,0,2025-04-02,58,0,0,0,0,0,0.00,2009-10-04,2017-08-13,4.52,4.68,4.16,4.97,5.00,4.95,4.58,NaN,False,1,1,0,0,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37142,1387539411036304965,https://www.airbnb.com/rooms/1387539411036304965,20250401230149,2025-04-02,city scrape,Sunny 2BR | Park Views | Skylights | Near 5 Tr...,Welcome to your Brooklyn brownstone retreat—br...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,4363605,https://www.airbnb.com/users/show/4363605,Conor,2012-12-09,"New York, NY",Townhouse owner in Brooklyn looking to share o...,within an hour,100.00,100.00,False,https://a0.muscache.com/im/pictures/user/1fd54...,https://a0.muscache.com/im/pictures/user/1fd54...,Bedford-Stuyvesant,4.00,8.00,False,True,t,Bedford-Stuyvesant,Bedford-Stuyvesant,Brooklyn,40.68,-73.91,Entire rental unit,Entire home/apt,4,1.00,1 bath,2.00,2.00,"[""Microwave"", ""Baking sheet"", ""Portable fans"",...",123.00,30,90,30.00,30.00,1125.00,1125.00,30.00,1125.00,NaN,True,1,31,61,336,2025-04-02,0,0,0,245,0,0,0.00,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,4,4,0,0,0.00
37143,1387704857063544317,https://www.airbnb.com/rooms/1387704857063544317,20250401230149,2025-04-02,city scrape,"Light filled, minimalist studio",Enjoy a stylish experience at this centrally-l...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2096643,https://www.airbnb.com/users/show/2096643,Kamiar,2012-04-08,"New York, NY",Professor of Statistics,NaN,NaN,NaN,False,https://a0.muscache.com/im/pictures/user/a7538...,https://a0.muscache.com/im/pictures/user/a7538...,NaN,1.00,1.00,False,True,t,East Village,East Village,Manhattan,40.73,-73.99,Entire rental unit,Entire home/apt,2,1.00,1 bath,1.00,1.00,"[""Air conditioning"", ""Washer"", ""Exterior secur...",108.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,NaN,True,0,29,59,334,2025-04-02,0,0,0,243,0,0,0.00,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1,1,0,0,0.00
37144,1387782293168469775,https://www.airbnb.com/rooms/1387782293168469775,20250401230149,2025-04-02,city scrape,Stylish Williamsburg Studio,"A big, bright, centrally located loft studio w...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,12100743,https://www.airbnb.com/users/show/12100743,Andrew,2014-02-10,"Sydney, Australia",Creative Director in advertising,NaN,NaN,NaN,False,https://a0.muscache.com/im/pictures/user/53927...,https://a0.muscache.com/im/pictures/user/53927...,Williamsburg,1.00,2.00,False,True,t,Williamsburg,Williamsburg,Brooklyn,40.71,-73.96,Entire rental unit,Entire home/apt,4,1.00,1 bath,0.00,3.00,"[""Air conditioning"", ""Lockbox"", ""TV"", ""Washer""...",166.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,NaN,True,30,60,90,365,2025-04-02,0,0,0,274,0,0,0.00,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,1,1,0,0,0.00
37145,1387820767264690075,https://www.airbnb.com/rooms/1387820767264690075,20250401230149,2025-04-02,city scrape,Habitación cerca de todo,Enjoy the simplicity of this quiet and central...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,582185509,https://www.airbnb.com/users/show/582185509,Lois Maikel,2024-06-07,"Santiago de los Caballeros, Dominican Republic",Not provided,within an hour,100.00,100.00,False,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,NaN,3.00,3.00,False,True,t,East Harlem,East Harlem,Manhattan,40.80,-73.94,Private room in rental unit,Private room,2,1.00,1 shared bath,1.00,1.00,"[""Air conditioning"", ""Outdoor dining area"", ""L...",72.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,NaN,True,23,53,83,358,2025-04-02,0,0,0,267,0,0,0.00,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,1,0,1,0,0.00
37146,1387893563515222060,https://www.airbnb.com/rooms/1387893563515222060,20250401230149,2025-04-02,city scrape,Stay Home,Keep it simple at this peaceful and centrally-...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,539608284,https://www.airbnb.com/users/show/539608284,Joyhefsiba,2023-09-29,NaN,Not provided,within a few hours,100.00,73.00,False,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Sheridan Hollow,7.00,7.00,False,True,t,Bushwick,Bushwick,Brooklyn,40.70,-73.93,Private room in rental unit,Private room,1,1.00,1 shared bath,1.00,1.00,"[""Air conditioning"", ""Wifi"", ""Smoke alarm""]",46.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,NaN,True,5,5,5,182,2025-04-02,0,0,0,91,0,0,0.00,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,6,0,6,0,0.00

## Remaining nulls

In [94]:
remaining_nulls = df.isnull().sum()
remaining_nulls = remaining_nulls[remaining_nulls > 0]

print(f"Final shape: {df.shape}")
print(f"\nRemaining nulls:\n{remaining_nulls}")

Final shape: (22118, 79)

Remaining nulls:
neighborhood_overview          10480
host_name                          2
host_since                         4
host_location                   5144
host_response_time              4077
host_response_rate              4077
host_acceptance_rate            3397
host_thumbnail_url                 4
host_picture_url                   4
host_neighbourhood              4337
host_listings_count                4
host_total_listings_count          4
calendar_updated               22118
first_review                    6809
last_review                     6809
review_scores_rating            6809
review_scores_accuracy          6809
review_scores_cleanliness       6809
review_scores_checkin           6809
review_scores_communication     6809
review_scores_location          6810
review_scores_value             6809
license                        17752
dtype: int64

In [95]:
# calendar_updated and license are not useful for analysis
df = df.drop(columns=['calendar_updated', 'license'], errors='ignore')
print("Dropped calendar_updated and license")

Dropped calendar_updated and license

In [96]:
# Host location and neighbourhood are optional profile fields — not critical
df['host_location'] = df['host_location'].fillna('Not provided')
df['host_neighbourhood'] = df['host_neighbourhood'].fillna('Not provided')
df['neighborhood_overview'] = df['neighborhood_overview'].fillna('Not provided')

# Host response fields — unknown means they haven't set it
df['host_response_time'] = df['host_response_time'].fillna('Unknown')
df['host_response_rate'] = df['host_response_rate'].fillna(0)
df['host_acceptance_rate'] = df['host_acceptance_rate'].fillna(0)

print("Host nulls filled")

Host nulls filled

In [97]:
# Listings with no reviews will have null review scores — this is valid
# Keep them but flag them separately
review_cols = [
    'review_scores_rating', 'review_scores_accuracy',
    'review_scores_cleanliness', 'review_scores_checkin',
    'review_scores_communication', 'review_scores_location',
    'review_scores_value'
]

# Fill with 0 to indicate no reviews yet
for col in review_cols:
    df[col] = df[col].fillna(0)

# Also fill first/last review dates
df['first_review'] = df['first_review'].fillna(pd.NaT)
df['last_review'] = df['last_review'].fillna(pd.NaT)

print("Review nulls filled")

Review nulls filled

In [98]:
# These columns have very few nulls (<5 rows) — safe to drop
tiny_null_cols = [
    'host_name', 'host_since', 'host_thumbnail_url',
    'host_picture_url', 'host_listings_count', 
    'host_total_listings_count'
]
df = df.dropna(subset=tiny_null_cols)
print(f"Shape after dropping tiny null rows: {df.shape}")

Shape after dropping tiny null rows: (22114, 77)

In [99]:
remaining = df.isnull().sum()
remaining = remaining[remaining > 0]

if len(remaining) == 0:
    print("✅ No nulls remaining — data is clean!")
else:
    print(f"Remaining nulls:\n{remaining}")

print(f"\nFinal clean dataset shape: {df.shape}")
print(f"Total listings: {len(df):,}")

Remaining nulls:
first_review    6808
last_review     6808
dtype: int64

Final clean dataset shape: (22114, 77)
Total listings: 22,114

In [100]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20250401230149,2025-04-02,city scrape,Superfast Wi-Fi. Clean & quiet home by the park,Renovated apt home in elevator building.,Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/3949d073-a02e...,2787,https://www.airbnb.com/users/show/2787,John,2008-09-07,"New York, NY",Educated professional living in Brooklyn. I l...,within an hour,100.00,81.00,False,https://a0.muscache.com/im/pictures/user/86745...,https://a0.muscache.com/im/pictures/user/86745...,Gravesend,4.00,13.00,False,False,True,Neighborhood highlights,Kensington,Brooklyn,40.65,-73.97,Private room in rental unit,Private room,2,1.00,1 private bath,1.00,1.00,"[""Microwave"", ""Portable fans"", ""Free street pa...",128.00,30,730,30.00,30.00,730.00,730.00,30.00,730.00,False,23,53,83,358,2025-04-02,9,0,0,267,0,0,0.00,2015-12-04,2018-10-19,4.89,4.88,5.00,5.00,5.00,4.75,4.88,False,4,0,4,0,0.08
1,6872,https://www.airbnb.com/rooms/6872,20250401230149,2025-04-02,city scrape,Uptown Sanctuary w/ Private Bath (Month to Month),This charming distancing-friendly month-to-mon...,This sweet Harlem sanctuary is a 10-20 minute ...,https://a0.muscache.com/pictures/miso/Hosting-...,16104,https://www.airbnb.com/users/show/16104,Kahshanna,2009-05-07,"New York, NY",A former life in fashion and wellness has left...,within a few hours,100.00,33.00,False,https://a0.muscache.com/im/pictures/user/d865a...,https://a0.muscache.com/im/pictures/user/d865a...,East Harlem,2.00,2.00,False,False,False,Neighborhood highlights,East Harlem,Manhattan,40.80,-73.94,Private room in condo,Private room,1,1.00,1 shared bath,1.00,1.00,"[""Dryer"", ""Elevator"", ""Hangers"", ""Hot water"", ...",59.00,30,180,30.00,30.00,180.00,180.00,30.00,180.00,False,23,53,83,83,2025-04-02,1,0,0,83,0,0,0.00,2022-06-05,2022-06-05,5.00,5.00,5.00,5.00,5.00,5.00,5.00,False,2,0,2,0,0.03
3,7801,https://www.airbnb.com/rooms/7801,20250401230149,2025-04-02,city scrape,Sunny Williamsburg Loft with Sauna,A huge loft in a repurposed factory building i...,We've lived here for over 15 years and love Wi...,https://a0.muscache.com/pictures/miso/Hosting-...,21207,https://www.airbnb.com/users/show/21207,Chaya,2009-06-12,"New York, NY",We're a couple in our thirties who love to tra...,within an hour,100.00,96.00,False,https://a0.muscache.com/im/pictures/user/d0391...,https://a0.muscache.com/im/pictures/user/d0391...,Williamsburg,4.00,4.00,False,False,True,Neighborhood highlights,Williamsburg,Brooklyn,40.72,-73.96,Entire place,Entire home/apt,2,1.00,1 bath,0.00,1.00,"[""Microwave"", ""Free street parking"", ""Drying r...",290.00,30,120,30.00,30.00,120.00,120.00,30.00,120.00,False,0,0,0,0,2025-04-02,13,1,0,0,1,60,17400.00,2009-08-09,2024-07-31,4.91,4.78,4.67,4.89,4.78,5.00,4.89,False,1,1,0,0,0.07
4,8490,https://www.airbnb.com/rooms/8490,20250401230149,2025-04-02,city scrape,"Maison des Sirenes1,bohemian, luminous apartment",Soak up the modern and vintage charm<br />of t...,Not provided,https://a0.muscache.com/pictures/1d0d9773-c829...,25183,https://www.airbnb.com/users/show/25183,Nathalie,2009-07-10,"New York, NY",I am French and have been living in Ny for 10...,within an hour,100.00,0.00,False,https://a0.muscache.com/im/users/25183/profile...,https://a0.muscache.com/im/users/25183/profile...,Bedford-Stuyvesant,2.00,3.00,False,False,True,Bedford-Stuyvesant,Bedford-Stuyvesant,Brooklyn,40.68,-73.94,Entire loft,Entire home/apt,5,1.00,1 bath,1.00,4.00,"[""Microwave"", ""Free street parking"", ""Drying r...",170.00,30,1125,30.00,30.00,1125.00,1125.00,30.00,1125.00,False,3,5,6,165,2025-04-02,190,0,0,75,0,0,0.00,2009-08-25,2023-10-16,4.77,4.83,4.74,4.88,4.88,4.67,4.76,False,2,2,0,0,1.00
5,9357,https://www.airbnb.com/rooms/9357,20250401230149,2025-04-02,city scrape,Midtown Pied-a-terre,PLEASE DO NOT REQUEST TO BOOK UNTIL WE HAVE ME...,Quiet residential block near many restaurants ...,https://a0.muscache.com/pictures/90036/4e60665...,30193,https://www.airbnb.com/users/show/30193,Tommi Laurelle,2009-08-06,"New York, NY",I am a spirit-minded alternative health practi...,Unknown,0.00,0.00,False,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Hell's Kitchen,1.00,1.00,False,False,True,Neighborhood highlights,Hell's Kitchen,Manhattan,40.77,-73.99,Entire rental unit,Entire home/apt,2,1.00,1 bath,1.00,1.00,"[""Free street parking"", ""Extra pillows and bla...",175.00,30,120,30.00,30.00,120.00,120.00,30.00,120.00,False,0,0,0,0,2025-04-02,58,0,0,0,0,0,0.00,2009-10-04,2017-08-13,4.52,4.68,4.16,4.97,5.00,4.95,4.58,False,1,1,0,0,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37142,1387539411036304965,https://www.airbnb.com/rooms/1387539411036304965,20250401230149,2025-04-02,city scrape,Sunny 2BR | Park Views | Skylights | Near 5 Tr...,Welcome to your Brooklyn brownstone retreat—br...,Not provided,https://a0.muscache.com/pictures/hosting/Hosti...,4363605,https://www.airbnb.com/users/show/4363605,Conor,2012-12-09,"New York, NY",Townhouse owner in Brooklyn looking to share o...,within an hour,100.00,100.00,False,https://a0.muscache.com/im/pictures/user/1fd54...,https://a0.muscache.com/im/pictures/user/1fd54...,Bedford-Stuyvesant,4.00,8.00,False,False,True,Bedford-Stuyvesant,Bedford-Stuyvesant,Brooklyn,40.68,-73.91,Entire rental unit,Entire home/apt,4,1.00,1 bath,2.00,2.00,"[""Microwave"", ""Baking sheet"", ""Portable fans"",...",123.00,30,90,30.00,30.00,1125.00,1125.00,30.00,1125.00,False,1,31,61,336,2025-04-02,0,0,0,245,0,0,0.00,NaT,NaT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,False,4,4,0,0,0.00
37143,1387704857063544317,https://www.airbnb.com/rooms/1387704857063544317,20250401230149,2025-04-02,city scrape,"Light filled, minimalist studio",Enjoy a stylish experience at this centrally-l...,Not provided,https://a0.muscache.com/pictures/miso/Hosting-...,2096643,https://www.airbnb.com/users/show/2096643,Kamiar,2012-04-08,"New York, NY",Professor of Statistics,Unknown,0.00,0.00,False,https://a0.muscache.com/im/pictures/user/a7538...,https://a0.muscache.com/im/pictures/user/a7538...,Not provided,1.00,1.00,False,False,True,East Village,East Village,Manhattan,40.73,-73.99,Entire rental unit,Entire home/apt,2,1.00,1 bath,1.00,1.00,"[""Air conditioning"", ""Washer"", ""Exterior secur...",108.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,False,0,29,59,334,2025-04-02,0,0,0,243,0,0,0.00,NaT,NaT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,False,1,1,0,0,0.00
37144,1387782293168469775,https://www.airbnb.com/rooms/1387782293168469775,20250401230149,2025-04-02,city scrape,Stylish Williamsburg Studio,"A big, bright, centrally located loft studio w...",Not provided,https://a0.muscache.com/pictures/hosting/Hosti...,12100743,https://www.airbnb.com/users/show/12100743,Andrew,2014-02-10,"Sydney, Australia",Creative Director in advertising,Unknown,0.00,0.00,False,https://a0.muscache.com/im/pictures/user/53927...,https://a0.muscache.com/im/pictures/user/53927...,Williamsburg,1.00,2.00,False,False,True,Williamsburg,Williamsburg,Brooklyn,40.71,-73.96,Entire rental unit,Entire home/apt,4,1.00,1 bath,0.00,3.00,"[""Air conditioning"", ""Lockbox"", ""TV"", ""Washer""...",166.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,False,30,60,90,365,2025-04-02,0,0,0,274,0,0,0.00,NaT,NaT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,False,1,1,0,0,0.00
37145,1387820767264690075,https://www.airbnb.com/rooms/1387820767264690075,20250401230149,2025-04-02,city scrape,Habitación cerca de todo,Enjoy the simplicity of this quiet and central...,Not provided,https://a0.muscache.com/pictures/hosting/Hosti...,582185509,https://www.airbnb.com/users/show/582185509,Lois Maikel,2024-06-07,"Santiago de los Caballeros, Dominican Republic",Not provided,within an hour,100.00,100.00,False,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Not provided,3.00,3.00,False,False,True,East Harlem,East Harlem,Manhattan,40.80,-73.94,Private room in rental unit,Private room,2,1.00,1 shared bath,1.00,1.00,"[""Air conditioning"", ""Outdoor dining area"", ""L...",72.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,False,23,53,83,358,2025-04-02,0,0,0,267,0,0,0.00,NaT,NaT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,False,1,0,1,0,0.00
37146,1387893563515222060,https://www.airbnb.com/rooms/1387893563515222060,20250401230149,2025-04-02,city scrape,Stay Home,Keep it simple at this peaceful and centrally-...,Not provided,https://a0.muscache.com/pictures/hosting/Hosti...,539608284,https://www.airbnb.com/users/show/539608284,Joyhefsiba,2023-09-29,Not provided,Not provided,within a few hours,100.00,73.00,False,https://a0.muscache.com/im/pictures/user/User/...,https://a0.muscache.com/im/pictures/user/User/...,Sheridan Hollow,7.00,7.00,False,False,True,Bushwick,Bushwick,Brooklyn,40.70,-73.93,Private room in rental unit,Private room,1,1.00,1 shared bath,1.00,1.00,"[""Air conditioning"", ""Wifi"", ""Smoke alarm""]",46.00,30,365,30.00,30.00,365.00,365.00,30.00,365.00,False,5,5,5,182,2025-04-02,0,0,0,91,0,0,0.00,NaT,NaT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,False,6,0,6,0,0.00